apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-1-prod-2
  namespace: akuity
spec:
  project: production

  source:
    repoURL: https://github.com/Nyati1/5g-simulation-v3.git
    targetRevision: main
    path: env/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: 5g-core-1-prod-2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true