# cluster-promotion-tasks.yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: git-update
spec:
  steps:
    - uses: noop
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: argocd-update
spec:
  steps:
    - uses: noop