apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: git-update
  namespace: 5g-network-simulation
spec:
  steps:
    - uses: git-clone
    - uses: kustomize-edit
    - uses: git-commit-push
      config:
        repoURL: https://github.com/Nyati1/5g-simulation-v3.git
        checkoutBranch: main
        outBranch: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: argocd-update
  namespace: 5g-network-simulation
spec:
  steps:
    - uses: argocd-sync
      config:
        apps:
          - name: 5g-sim-dev
            namespace: argocd