apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: 5g-network-simulation
  namespace: 5g-network-simulation
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
  - stageSelector:
      name: staging
    autoPromotionEnabled: true