---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: 5g-network-simulation
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: 5g-sim-warehouse
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: 5g-network-simulation
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: 5g-sim-warehouse
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: 5g-network-simulation
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: 5g-sim-warehouse