apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: 5g-network-simulation
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: 5g-sim-warehouse
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/Nyati1/5g-simulation-v3.git
        - name: imageRepo
          value: docker.io/gradiant/open5gs

      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./src
              - branch: env/dev
                create: true
                path: ./out

        - uses: git-clear
          config:
            path: ./out

        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/env/dev
            images:
              - image: ${{ vars.imageRepo }}
                tag: 2.7.0

        - uses: kustomize-build
          config:
            path: ./src/env/dev
            outPath: ./out/manifests.yaml

        - uses: git-commit
          config:
            path: ./out
            message: "update image"

        - uses: git-push
          config:
            path: ./out
            targetBranch: env/dev

        - uses: argocd-update
          config:
            apps:
              - name: 5g-sim-dev
                namespace: argocd