apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-amf
  namespace: 5g-core-1
  labels:
    app: open5gs-amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-amf
  template:
    metadata:
      labels:
        app: open5gs-amf
    spec:
      containers:
      - name: amf
        image: docker.io/gradiant/open5gs:2.7.0
        imagePullPolicy: IfNotPresent
        args:
          - open5gs-amfd
        env:
          - name: OGS_LOG_LEVEL
            value: error  
          - name: MCC
            valueFrom:
              configMapKeyRef:
                name: open5gs-config
                key: mcc
          - name: MNC
            valueFrom:
              configMapKeyRef:
                name: open5gs-config
                key: mnc