apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-amf
spec:
  replicas: 1 # Added for clarity
  selector:
    matchLabels:
      app: open5gs-amf # This must match the template labels below
  template:
    metadata:
      labels:
        app: open5gs-amf # This identifies the pods created by this deployment
    spec:
      containers:
         - name: open5gs-amf
           args:
            - open5gs-amfd
           image: docker.io/gradiant/open5gs:2.7.0
           imagePullPolicy: IfNotPresent
        
      env:
        - name: MCC
          valueFrom:
            configMapKeyRef:
              name: open5gs-config
              key: mcc
        - name: MNC
          valueFrom:
            configMapKeyRef:
              name: open5gs-config
              key: mnc