apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 5g-network-simulation:apps/Deployment:5g-lab/open5gs-upf
  name: open5gs-upf
  namespace: 5g-lab
spec:
  replicas: 4
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      containers:
        - args:
            - open5gs-upfd
          image: docker.io/gradiant/open5gs:2.7.0
          name: upf
          ports:
            - containerPort: 2152
              name: gtpu
              protocol: UDP
          securityContext:
            privileged: true
